# Build validation

name: Build

on:
  push:
    branches-ignore:
      - experimental/**
  pull_request:
    branches-ignore:
      - experimental/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Build and verify
        run: mvn -s ./.maven-settings.xml -Pcontinuous-integration -B -U clean verify
